export const actionTypes = {
    GET_CLUSTERS: "GET_CLUSTERS",
    CLUSTERS_RECIEVED: "CLUSTERS_RECIEVED"
};


export const actionLoginTypes = {
    LOGGING_OUT:"LOGGING_OUT",
    LOG_OUT: "LOG_OUT",
    GET_USER: "GET_USER",
    USER_RECIEVED: "USER_RECIEVED",
    USER_ERROR: "USER_ERROR",
    POST_USER: "POST_USER",
    SET_USER_FETCHING: "SET_USER_FETCHING",
    GET_CODE: "GET_CODE",
    FORGOT_PASSWORD: "FORGOT_PASSWORD",
    CHANGE_PASSWORD: "CHANGE_PASSWORD",
};

export const actionEventTypes = {
    EVENT_ERROR:"EVENT_ERROR",
    RECEIVED_EVENT_DATA:"RECEIVED_EVENT_DATA",
    SET_EVENT_FETCHING: "SET_EVENT_FETCHING",
    CREATE_EVENT: "CREATE_EVENT",
}
